### ISSUE TITLE
one-shot SCF way vs K-path way

### ISSUE THREAD

**Issue by Laodbz** [Infant83/VASPBERRY#12]
Dear Hyun-Jung Kim:

First of all, thank you very much for sharing this code. 

In use, I noticed that when using 'one-shot SCF' to get berry curvature, the unit is A^-2 (in the BERRYCURV.dat file); To calculate berry curvature along high symmetry path, the unit is A^2 (in the BERRYCURV_KUBO.dat file); The above ways get difference values (for example, on the K point of high symmetry in the case of MoS2, the 'one-shot SCF' method's value is -12.23 A^-2, while the value is -26.4 A^2 using the K-path way). Are the results of these two kinds of berry curvature obtained from the same material equivalent? Can you provide some literature on these two formulas for calculating berry curvature? 

Thank you again！
Best regards！
Laodbz

**Comment by Infant83** [comment]
Yes, this is good point. But first of all, I apologize this late response. 
The method from KUBO is based on linear response theory and it only dealing with the single k-point. The derivation taken directly from the Hamiltonian since the TB Hamiltonian is written analytically. The problem in this approach is that to take the integral over the BZ, it should be greatly cautious since we are particularly pointing out single k-point. By the way, in Fukui's method, it takes phase accumulation over the path of small patch and is not highly suffered from the k-point grid mesh size over the BZ. Of course, if you take much finer k-grid, the result will be improved but it fastly approaches its convergence. By the way, Kubo's method, I think it is not easy to get convergence. Imagine, your k-point, points some singular values of Berry curvature in Kubo's method since this point is band crossing point, then the integral will be diverges, since it just multiplied with the size of the small k-path around it. Hence, I suggest you to use Fukui's method in calculating the Chern number. But still, the Kubo's approach is also the good way to see how the Berry curvature distributes over the whole BZ.
