### ISSUE TITLE
How to find Z2 number between bands n and n+1? 

### ISSUE THREAD

**Issue by Matephysics** [Infant83/VASPBERRY#6]
Dear Hyun-Jung Kim,
I am a Ph.D. student. I am interested in topological properties such as Berry curvature, Chern number, etc. In this sense, i am learning to use your code "vaspberry". Many thanks for this awesome code. I have some confusion and question, please help to clarify it:
(1) I am interested to find a Z2 number. How to find Z2 number between bands n and n+1? 
(2) What is the command line for Cher number calculation? Suppose, how can i find the Chern number between the bands n and n+1?
(3) What is the command line for Berry curvature for the nth band? 
(4) How to find the Quantum Anomalous Hall effect conductivity?
(5) I repeat the example of MoS2 for Berry curvature calculation. The calculation runs successfully. However, when i use the script contour.py (python contour.py), it gives the error (see the attached image).
I would be very highly thankful to you in this regard. Looking forward to your nice response. 
Thank You
![error](https://user-images.githubusercontent.com/49361150/91329290-9112f380-e7fa-11ea-917e-8b13bb866f10.JPG)

**Comment by Infant83** [comment]
(1) I am interested to find a Z2 number. How to find Z2 number between bands n and n+1?
=> This code does not find Z2 number for the certain band.
(2) What is the command line for Cher number calculation? Suppose, how can i find the Chern number between the bands n and n+1?
=> vaspberry -ii n -if n+1 -s 2  -kx nkx -ky nky 
for -s option : (soc 2, no-soc 1)
But in this case, please make sure that n and n+1 the bands are isolated from the other bands for the whole BZ, otherwise it will be messed up..

(3) What is the command line for Berry curvature for the nth band?
=> vaspberry -is n -s 2  -kx nkx -ky nky
Here, -is option takes single integer value "n" which indicates n-th band.

(4) How to find the Quantum Anomalous Hall effect conductivity?
==> We are work on this feature for the next update version, but not in the near future I guess..
There are some things to check up. 
If you mean that how to make sure some system is QAH or not, this can be judged by non zero chern number.
But, QAH conductivity calculations need berry curvature information for every eigenstate of n-th level and k-points Omega(n,k), we are currently working on that.

(5) I repeat the example of MoS2 for Berry curvature calculation. The calculation runs successfully. However, when i use the script contour.py (python contour.py), it gives the error (see the attached image).
=> It is related to the version of your python. If you use python3 then, have a try with following syntax for print. 
ex: print("xxx")
